exclude: [casual-game-tutorial, random_mentor_dates] 
title: CoderDojo Göteborg
name: CoderDojo Göteborg
email: gothenburg@coderdojo.com
description: Vi vill inspirera barn och ungdomar att uttrycka sig och vara kreativa genom programmering.

display_footer: initial  #change this to 'none' if you want to hide the footer copyright text

theme: jekyll-material-theme

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

# Settings for the porfolio section

portfolio_heading: Börja programmera
portfolio_type: cards #cards or carousel

project_one: En del av något större
project_one_description: CoderDojo är ett globalt initiativ som finns i över 100 länder med nästan 2000 lokalavdelningar. På hemsidan finns mer information, kontaktuppgifter till alla lokalavdelningar och användbara länkar för att komma igång med programmering.
project_one_url: https://coderdojo.com/
project_one_icon: group # these are from materiailize css, the full collection is here: http://materializecss.com/icons.html

project_two: Börja här
project_two_description: Om du aldrig programmerat innan så har code.org en massa spännande utmaningar.
project_two_url: https://code.org
project_two_icon: flight_takeoff


project_three: Nästa steg
project_three_description: Nästa steg är att lära sig ett programmeringsspråk. Vi i CoderDojo Göteborg har valt javascript då det är lätt tillgängligt direkt i din webbläsare. Codecademy är ett väldigt bra ställe att börja på men kräver tyvärr att man kan engelska.
project_three_url: https://www.codecademy.com/learn/introduction-to-javascript
project_three_icon: directions_walk


project_four: Skapa ett spel från grunden
project_four_description: Ett gäng utmaningar som, efter genomförande, förhoppningsvis gett tillräckligt med verktyg för att bygga ett enkelt 2D-spel!
project_four_url: https://coderdojogbg.org/casual-game-tutorial/index.html
project_four_icon: directions_run

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Ta mig dit

github: https://github.com/gbgcoderdojo/gbgcoderdojo.github.io
facebook: https://www.facebook.com/coderdojogothenburg

baseurl: # If your site is located at /blog or /home, change it here, otherwise leave it empty
url: http://localhost:4000/ # The URL of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

# cookie_accept_message: Thanks! # The pop-up dialog that appears after accepting the cookie notice.

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
